name: cadastro_app
description: App de Cadastro Unificado - Web

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.1.1
  connectivity_plus: ^4.0.2
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^16.0.0
  
  # Utils
  intl: ^0.19.0
  mask_text_input_formatter: ^2.5.0
  
  # Loading & UI
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  
  # Forms
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700